version: '3.8'

networks:
    app-network:
volumes:
    app-data:
services:
    nginx:
        image: nginx:1.21.6-alpine
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - .docker/nginx:/etc/nginx/conf.d
        networks:
            app-network:
    app:
        build:
            context: .docker/php
            dockerfile: dockerfile
        volumes:
            - ./:/var/www
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            app-network:
    mysql:
        image: mysql:latest
        platform: linux/x86_64
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./.mysql:/var/lib/mysql
        networks:
            app-network:
